### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by phated** [jonschlinkert/object.reduce#1]
I think it would be cool to use some of the `obect.*` and other microlibs you've created; however, I have some open questions that really effect my decisions:
1. Can you commit to supporting node 0.10 and 0.12 for a year+ for the modules? This is a big deal for me because that is the projection seldo made on twitter for node 0.10 usage.
2. How do you feel about a "neutral ground" for the modules I pull into the gulp tree? You've typically been a great maintainer on the modules we've used, but I've recently been burnt by the BDFL model.
3. Can you add Windows testing?  It's something I'm trying to get added in many places, even if the OS doesn't effect the module specifically.
4. Are you open to Major bumping everything below 1.0?  I really want to get everything 1.0+ to really benefit from semver.

**Comment by phated** [comment]
Thanks for the invite.  I'm not sure if that is enough of a "neutral ground" though, as you could still remove me if we had a disagreement (see: burnt by BDFL).

**Comment by jonschlinkert** [comment]
@phated thanks for the questions, I'm on vacation until Saturday. I can still respond sometimes but will have more time when I get back

> Can you commit to supporting node 0.10 and 0.12 for a year+ for the modules?

Definitely, @doowb and I are both on board with this view, for a number of reason we can discuss another time - but probably the same reasons you're asking. 

> How do you feel about a "neutral ground" for the modules I pull into the gulp tree

It depends on the module. I'm all for collaborating and consolidating efforts.  I've been on orgs that have the exact same issue, and IMHO there is little to no difference at all in terms of mitigating risk. 

For example:

<img width="688" alt="screen shot 2016-10-06 at 5 17 52 pm" src="https://cloud.githubusercontent.com/assets/383994/19171046/e39e3ffa-8be8-11e6-9cf5-13a03e56af79.png">

We can discuss this further, but it seems like something that would be better for a IRC or phone if necessary. 

> Can you add Windows testing? It's something I'm trying to get added in many places, even if the OS doesn't effect the module specifically.

absolutely, we've talked about this a lot lately. It's something we need to do regardless of whether or not the modules are used in gulp.

> Are you open to Major bumping everything below 1.0? I really want to get everything 1.0+ to really benefit from semver.

I'm okay with bumping modules to 1.0. IMHO it makes it harder to tell when modules are truly mature - there is no possible way a new release qualifies as a 1.0 before it's ever used, but I don't care enough to lose sleep over it.

**Comment by phated** [comment]
Maybe an organization isn't the answer.  Github has so much to be desired.

**Comment by phated** [comment]
I think these have been thoroughly answered.
